name: Generate Contribution Snake

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:      # Allows manual triggering
  push:
    branches:
      - main             # Runs when pushing to main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      # Generate the snake animation
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: Vuthy-Tourn
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Commit the generated files
      - name: Commit files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push
