name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/snake.svg
            output/snake-dark.svg?palette=github-dark
          
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add output/
          git commit -m "Update snake animation"
          git push
